# Application
spring.application.name=sftp-manager
server.port=8080

# PostgreSQL DataSource
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sftpmanager}
spring.datasource.username=${DB_USER:sftpmanager}
spring.datasource.password=${DB_PASSWORD:changeme}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss

# Logging
logging.level.com.sftpmanager=INFO
logging.level.org.springframework.security=WARN

spring.security.oauth2.client.registration.google.client-id=814158618541-c7scpk06uaj70nebnhknufv04i7an09j.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile