apiVersion: v1
kind: Service
metadata:
  name: sftp-manager-service
  namespace: sftp-manager
  annotations:
    cloud.google.com/backend-config: '{"default": "sftp-manager-backend-config"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: sftp-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
